### ISSUE TITLE
Submodule import issue

### ISSUE THREAD

**Issue by bearwmceo** [TooTallNate/node-socks-proxy-agent#100]
Hi there,

Recently I've detected an issue on node-socks-proxy-agent and same for https proxy agent.
When you import socks-proxy-agent in a package.json from a git submodule (when you use it as a workspace), it generates some issues, most probably it is caused due to certificate imports.

Please review postinstalls or imports in code, it seems somewhere is a mispath.

**Comment by Kikobeats** [comment]
Hello, I'm going to close this since the library doesn't have a postinstall script.

If you add more information, I can try to help you, but with this I can't do too much.
