### ISSUE TITLE
how connect to shadowsocks server?

### ISSUE THREAD

**Issue by Taoja** [TooTallNate/node-socks-proxy-agent#106]
my shadowsocks server is:
```bash
Congratulations, Shadowsocks-go server install completed!
Your Server IP        :  120.77.99.104 
Your Server Port      :  9999 
Your Password         :  ***
Your Encryption Method:  aes-256-cfb 
```
i try options like this when using socks-proxy-agent to connect shadowsocks server:
```js
const agent = new SocksProxyAgent({
  hostname: '120.77.99.104',
  port: 9999,
  protocol: 'socks5',
  password: '***',
  custom_auth_method: 'aes-256-cfb',
});
axios.options.httpAgent = agent
```

i got a error after send a request:
```
Error: Received invalid Socks5 initial handshake (invalid socks version)
```

**Comment by TooTallNate** [comment]
This code in this repository has been moved to the [`proxy-agents` monorepo](https://github.com/TooTallNate/proxy-agents), so I am closing this pull request. If you feel that this issue still exists as of the latest release, feel free to open a new issue over there.
