### ISSUE TITLE
npm version out of date?

### ISSUE THREAD

**Issue by pandaiolo** [TooTallNate/node-socks-proxy-agent#14]
I have an issue with `https.get` used in `mailjet` always trying to connect to `localhost` when called with a string as argument (the url). I traced down the bug to `agent-base` version <4.0 when `options`  is tested instead of `_options`.

**TL;DR**

In `socks-proxy-agent`, the recent dependency to `agent-base` version `^4.1.0` seem OK in the master, but not in npm:

```
{ name: 'socks-proxy-agent',
  description: 'A SOCKS proxy `http.Agent` implementation for HTTP and HTTPS',
  'dist-tags': { latest: '3.0.0' },
  versions:
   [ '0.0.1',
     ...
     '3.0.0' ],
...
  dependencies: { 'agent-base': '^4.0.1', socks: '^1.1.10' },
  devDependencies: { mocha: '^3.4.2', 'raw-body': '^2.2.0', socksv5: '0.0.6' },
  ...
```

Could you update the npm version to current? (master was updated on jun 27, while npm version is from jun 13, despite the same version number)

Thanks!

**Comment by pandaiolo** [comment]
Hi ! Any news about this ?

**Comment by TooTallNate** [comment]
Hey @pandaiolo, sorry for missing this. v3.0.1 is published to npm. Let me know if that fixed things for you please.

**Comment by pandaiolo** [comment]
Hey @TooTallNate thanks for updating the npm version. I did a fresh `npm install` on my project but the issue is not gone :( I still get the `4.1.0` version of `agent-base` package dependency, which contains the bug, instead of `4.1.1`. 

Despite the `package.json` now asking for `^4.1.0` 

I though this semver declaration would download the last version (`4.1.1`) but it does not. Am I doing something wrong or the dependency version to `agent-base` has to be bumped to `4.1.1`?

Thanks

**Comment by pandaiolo** [comment]
My bad, it was the npm locking mechanism which held the version update.

I removed the lock and the version is now updated. Thanks!
