### ISSUE TITLE
Only accept IP address when creating instance

### ISSUE THREAD

**Issue by ricalhsieh** [TooTallNate/node-socks-proxy-agent#17]
I'm using with request v2.85.0.
Putting domain name when creating the instance will get following error:

```
node_modules/socks/build/common/helpers.js:30
        throw new util_1.SocksClientError(constants_1.ERRORS.InvalidSocksClientOptionsProxy, options);
        ^
```

If creating using the IP address such as "socks://127.0.0.1", it's OK.

**Comment by talmobi** [comment]
Is host name resolving out of scope for this module?

Seems like the underlying socks module never officially supported host resolving for proxy addresses:

docs v1: https://github.com/JoshGlazebrook/socks/tree/82d83923ad960693d8b774cafe17443ded7ed584
docs v2: https://github.com/JoshGlazebrook/socks
migration guide: https://github.com/JoshGlazebrook/socks/blob/master/docs/migratingFromV1.md

But it did resolve them in v1 implicitly, not so in v2 anymore.

**Comment by talmobi** [comment]
@knoxcard That's the destination address, not the proxy address.

**Comment by JoshGlazebrook** [comment]
fyi: https://github.com/JoshGlazebrook/socks has been updated to allow hostnames for the proxy address.
