### ISSUE TITLE
Counts of proxy usages

### ISSUE THREAD

**Issue by kn9ka** [TooTallNate/node-socks-proxy-agent#23]
Hi, I have pool of proxies and want to count their usages for determinate how many times one proxy was used for connect, could I do it without forking and adding this functional?

I'm already try to scan response after each fetch, but do not see anything about it :(
I need it for know that keep-alive works.

ty

**Comment by Kikobeats** [comment]
Hum, I think it can be as simple as override the `callback` method to add some wrapping for counting

https://github.com/TooTallNate/node-socks-proxy-agent/blob/master/src/agent.ts#L146
