### ISSUE TITLE
Pass timeout to SocksClient to prevent open sockets

### ISSUE THREAD

**Issue by berstend** [TooTallNate/node-socks-proxy-agent#26]
Hey there,
thanks a lot for the agents - they're really useful. 👍 

I ran into an issue with socks proxy sockets not being closed properly,
which expressed itself in the node process not shutting down in time.

The following is an example of a "faulty" socks proxy (it's actually a http proxy):

```es6
const agent = new ProxyAgent('socks5://163.172.173.187:3000')
agent.timeout = 1 * 1000 // socket timeout, relevant for socks
```

The above will correctly timeout the connection after 1 second (agent-base functionality),
but the underlying socket used by `socks` remains open for the default timeout of 30s.

The fix is very simple (I confirmed it's working), we just have to pass the `timeout` property to [the socks client](https://github.com/TooTallNate/node-socks-proxy-agent/blob/master/index.js#L118) ([Socks docs](https://github.com/JoshGlazebrook/socks#socksclientoptions)).

I'd love to present you a finished PR for this small fix, but unfortunately I'm somehow unable to find a way to use the existing `timeout` property from the [agent-base Class](https://github.com/TooTallNate/node-agent-base/blob/master/index.js#L39). 😅

Would be great if you could have a quick look, if you could tell me how to re-use the existing timeout property I'm happy to submit a PR.

Thanks!

**Comment by berstend** [comment]
As this was blocking I did a quick fork and abused the proxy options object. 😄 

```bash
yarn add berstend/node-socks-proxy-agent-with-timeout
```

```typescript
import * as ProxyAgent from 'proxy-agent'
import * as SocksProxyAgentWithTimeout from 'socks-proxy-agent-with-timeout'

const agent = new ProxyAgent({
  protocol: 'socks5:',
  hostname: '163.172.173.187',
  port: '3000',
  timeout: 3 * 1000, // socks timeout
  proxies: {
    socks5: SocksProxyAgentWithTimeout
  }
})
agent.timeout = 1 * 1000 // general proxy agent timeout
```

**Comment by Kikobeats** [comment]
Closing because a timeout is already associated with the connect command:
https://github.com/TooTallNate/node-socks-proxy-agent/blob/master/src/agent.ts#L166
