### ISSUE TITLE
Allow protocol strings that do not end with colon ':'

### ISSUE THREAD

**Issue by blake-regalia** [TooTallNate/node-socks-proxy-agent#27]
From `proxy-agent`, one should be able to pass the options object:

```js
proxy_agent({
   protocol: 'socks5',
   host: '127.0.0.1',
   port: 8182,
});
```

However, once it calls `socks-proxy-agent` constructor then [this block](https://github.com/TooTallNate/node-socks-proxy-agent/blob/master/index.js#L53) throws an exception at the default case since protocol does not end in `:`.

**Comment by knoxcard** [comment]
i agree, 'socks5:' is ridiculous, should just be 'socks5'

**Comment by TooTallNate** [comment]
The reason that it was implementing like that is because the result of `url.parse()` includes the `:`. PR welcome to support both formats though.

**Comment by Kikobeats** [comment]
Closing because even ridiculous is what WHATWG URL does:

```
new URL('https://example.com')
URL {
  href: 'https://example.com/',
  origin: 'https://example.com',
  protocol: 'https:',
  username: '',
  password: '',
  host: 'example.com',
  hostname: 'example.com',
  port: '',
  pathname: '/',
  search: '',
  searchParams: URLSearchParams {},
  hash: ''
}
```
