### ISSUE TITLE
Error when using socks-proxy-agent as a globalAgent

### ISSUE THREAD

**Issue by charlyx** [TooTallNate/node-socks-proxy-agent#39]
Hi 👋 

First of all, thanks for your work!
We're using it every day in order to access private services during our development using an SSH connection with dynamic port forwarding to a bastion.

It is now possible to override `http.globalAgent`. It will help us remove the agent from our client and other dependencies will then be able call those private services as well.
I tried to override `http.globalAgent` giving a `new SocksProxyAgent` instead but it throws the following error:

```js
_http_client.js:142
    throw new ERR_INVALID_PROTOCOL(protocol, expectedProtocol);
    ^

TypeError [ERR_INVALID_PROTOCOL]: Protocol "http:" not supported. Expected "undefined"
    at new ClientRequest (_http_client.js:142:11)
    at request (http.js:44:10)
    at Object.get (http.js:48:15)
    at Object.<anonymous> (/Users/charly/Work/pro/MMB/starship/packages/stargate-backend/test.js:11:6)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:822:10)
    at internal/main/run_main_module.js:17:11
```

❌ Here is the code I used:

```js
const http = require('http')
const SocksProxyAgent = require('socks-proxy-agent')

http.globalAgent = new SocksProxyAgent(process.env.HTTP_PROXY)

http.get('private url', console.log)
```

✅ It is only working when used as an agent in the request options:
```js
const http = require('http')
const SocksProxyAgent = require('socks-proxy-agent')

http.get('private url', {
  agent: new SocksProxyAgent(process.env.HTTP_PROXY),
}, console.log)
```

```
node version: v12.2.0
```

What did I do wrong? Do you get why it is not working when used as a `globalAgent`?
Is it possible to make it work?

I'm quite keen on implementing a solution and then opening a PR if you give me a solution 😅

Thanks in advance for your help! 🙏

**Comment by TooTallNate** [comment]
Can you try with v5.0.0? This should be fixed at this point.
