### ISSUE TITLE
Client network socket disconnected before secure TLS connection was established

### ISSUE THREAD

**Issue by ZHlambo** [TooTallNate/node-socks-proxy-agent#45]
want i connect to wss, it's throw this error;
```

var WebSocket = require('ws');
var SocksProxyAgent = require('socks-proxy-agent');

// SOCKS proxy to connect to
var proxy = process.env.socks_proxy || 'socks://127.0.0.1:50984';
console.log('using proxy server %j', proxy);

// WebSocket endpoint for the proxy to connect to
var endpoint = process.argv[2] || 'wss://api.huobi.pro/ws';
console.log('attempting to connect to WebSocket %j', endpoint);

// create an instance of the SocksProxyAgent class with the proxy server information
var agent = new SocksProxyAgent(proxy);

// initiate the WebSocket connection
var socket = new WebSocket(endpoint, { agent: agent });

socket.on('open', function () {
  console.log('"open" event!');
  // socket.send('hello world');
});

socket.on('message', function (data, flags) {
  console.log('"message" event! %j %j', data, flags);
  socket.close();
});
```

**Comment by sashahohloma** [comment]
I've got the same error when using many of different socks5 proxy. Error `Client network socket disconnected before secure TLS connection was established` thrown as uncaught error even inside try...catch block. My solution is add error listener after create tls connection.
For fast test you need to replace this code:

```
return tls.connect({
    ...omit(opts, 'host', 'hostname', 'path', 'port'),
    socket,
    servername
});
```

on this code:
```
const tlsConnection = tls.connect({
    ...omit(opts, 'host', 'hostname', 'path', 'port'),
    socket,
    servername
});
tlsConnection.on('error', () => {
    return null;
});
return tlsConnection;
```

I tried to write `throw error` inside error listener, but error still throws as uncaught error. I don't know why error from agent becomes as uncaught inside try...catch block, maybe somebody knows better solution.

**Comment by zzzhan** [comment]
Try to  correct your URL and PORT.

**Comment by bossturk** [comment]
> I've got the same error when using many of different socks5 proxy. Error `Client network socket disconnected before secure TLS connection was established` thrown as uncaught error even inside try...catch block. My solution is add error listener after create tls connection. For fast test you need to replace this code:
> 
> ```
> return tls.connect({
>     ...omit(opts, 'host', 'hostname', 'path', 'port'),
>     socket,
>     servername
> });
> ```
> 
> on this code:
> 
> ```
> const tlsConnection = tls.connect({
>     ...omit(opts, 'host', 'hostname', 'path', 'port'),
>     socket,
>     servername
> });
> tlsConnection.on('error', () => {
>     return null;
> });
> return tlsConnection;
> ```
> 
> I tried to write `throw error` inside error listener, but error still throws as uncaught error. I don't know why error from agent becomes as uncaught inside try...catch block, maybe somebody knows better solution.

Can you explain in detail what exactly you changed?

**Comment by TooTallNate** [comment]
This code in this repository has been moved to the [`proxy-agents` monorepo](https://github.com/TooTallNate/proxy-agents), so I am closing this pull request. If you feel that this issue still exists as of the latest release, feel free to open a new issue over there.
