### ISSUE TITLE
Property agent doesn't exists on URLWithStringQuery

### ISSUE THREAD

**Issue by shirshak55** [TooTallNate/node-socks-proxy-agent#48]
The examples uses url parsing 
```
    function parse(urlStr: string): UrlWithStringQuery;
```

UrlWithStringQuery inherits URL
The problem is it returns the type URL which has following interface 
```
    interface Url {
        auth: string | null;
        hash: string | null;
        host: string | null;
        hostname: string | null;
        href: string;
        path: string | null;
        pathname: string | null;
        protocol: string | null;
        search: string | null;
        slashes: boolean | null;
        port: string | null;
        query: string | null | ParsedUrlQuery;
    }
```

there is no agent here. It means typescript will complain and I think it is a valid complain too.

Is there anything we can do to fix this.

The typescript branch also uses Agent (agent-base) which seems to be incompatible with http.Agent.

Please let me know if there is easy way to get rid of this error.

**Comment by shirshak55** [comment]
@TooTallNate  let me know if there is any fix. Thanks

**Comment by TooTallNate** [comment]
Probably use the 3-argument version of `http.request()` is the easiest way, like in the [TypeScript example in the README](https://github.com/TooTallNate/node-socks-proxy-agent#typescript-example):

```ts
import https from 'https';
import { SocksProxyAgent } from 'socks-proxy-agent';

const info = {
  host: 'br41.nordvpn.com',
  userId: 'your-name@gmail.com',
  password: 'abcdef12345124'
};
const agent = new SocksProxyAgent(info);

https.get('https://jsonip.org', { agent }, (res) => {
  console.log(res.headers);
  res.pipe(process.stdout);
});
```
