### ISSUE TITLE
Onion sites aren't working

### ISSUE THREAD

**Issue by leeceeksdee** [TooTallNate/node-socks-proxy-agent#54]
I have this code:

```
var http = require('http'),
    httpProxy = require('http-proxy'),
    ProxyAgent = require('proxy-agent');

var proxy = httpProxy.createProxyServer({
  agent: new ProxyAgent('socks5://127.0.0.1:9050'),
  target:'http://XXXXXXXXXXXX.onion'
}).listen(3000);

proxy.on('error', function (err, req, res) {
  res.writeHead(502, {
    'Content-Type': 'text/plain'
  });
 console.log(err)
  res.end('Something went wrong.');
});
```

and it doesn't work because `proxy-agent` doesn't make DNS requests through the SOCKS5 proxy. Can you add an option for it to do this? Thanks.

**Comment by TooTallNate** [comment]
Try using `socks://` or `socks5h://` as the protocol, then the lookups will happen from the DNS server. See [here](https://github.com/TooTallNate/node-socks-proxy-agent/blob/8ed8efa99c8a17a8ee52872728f13a94497ddc13/src/agent.ts#L62-L65) for the implementation.

**Comment by leeceeksdee** [comment]
Thanks, sorry for bothering you.
