### ISSUE TITLE
Working example with Undici

### ISSUE THREAD

**Issue by NN-Binary** [TooTallNate/node-socks-proxy-agent#69]
Hi,

I can't seem to find any working example anywhere with it working with Undici (the newest and faster HTTP Client from official NodeJS).

I've however seen multiple users inquiring about it, including on Stackoverflow without any reply so far.
From March 2021: http://5.9.10.113/66459770/how-to-use-authenticated-proxies-with-undici

**Comment by Kikobeats** [comment]
Hello, hard to say since I'm not an Undici user, so I'm going to keep this open until someone decide to improve docs in this aspect 🙂

**Comment by NN-Binary** [comment]
That would be really great! A lot of users in Undici (which will be the new standard soon) as it's made by official NodeJS team are awaiting it

**Comment by TooTallNate** [comment]
This code in this repository has been moved to the [`proxy-agents` monorepo](https://github.com/TooTallNate/proxy-agents), so I am closing this pull request. If you feel that this issue still exists as of the latest release, feel free to open a new issue over there.
