### ISSUE TITLE
Set custom header on socks proxy

### ISSUE THREAD

**Issue by Thomasbrighton** [TooTallNate/node-socks-proxy-agent#77]
Hello, I couldn't find set custom headers tutorial in document. I'm using below code for this purpose but I don't know it is true.

Could you answer the correct way of set custom headers on socks proxy agent please?

```
const proxy = {
     proxy: '137.77.140.101:1085',
     userAgent: 'Mozilla/5.0 (Linux; Android 11; LM-Q720) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.105 Mobile Safari/537.36',
};
const options = url.parse('socks://' + proxy.proxy);
options.headers = {
      'User-Agent': proxy.userAgent,
};
const agent = new SocksProxyAgent(options);
ws = new WebSocket('wss://domain.com', { agent: agent, handshakeTimeout: 10000 });
```

**Comment by Jakeroid** [comment]
Maybe I am wrong, but...

`
const proxy = {
     proxy: '137.77.140.101:1085',
     userAgent: 'Mozilla/5.0 (Linux; Android 11; LM-Q720) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.105 Mobile Safari/537.36',
};
const options = url.parse('socks://' + proxy.proxy);
const headers = {
      'User-Agent': proxy.userAgent,
};
const agent = new SocksProxyAgent(options);
ws = new WebSocket('wss://domain.com', { agent: agent, headers: headers, handshakeTimeout: 10000 });
`

**Comment by TooTallNate** [comment]
This code in this repository has been moved to the [`proxy-agents` monorepo](https://github.com/TooTallNate/proxy-agents), so I am closing this pull request. If you feel that this issue still exists as of the latest release, feel free to open a new issue over there.
