### ISSUE TITLE
Incorrect lookup for socks5

### ISSUE THREAD

**Issue by ukrexpo** [TooTallNate/node-socks-proxy-agent#91]
In "socks-proxy-agent" version 6.1.1 found that "lookup = true" for protocol "socks5", while "lookup = false" for "socks" and "socks5h" (file /node_modules/socks-proxy-agent/dist/agent.js, lines 56-74):
```
switch (opts.protocol.replace(':', '')) {
	case 'socks4':
		lookup = true;
	// pass through
	case 'socks4a':
		type = 4;
		break;
	case 'socks5':
		lookup = true;
	// pass through
	case 'socks': // no version specified, default to 5h
	case 'socks5h':
		type = 5;
		break;
	default:
		throw new TypeError(`A "socks" protocol must be specified! Got: ${opts.protocol}`);
}
```

Protocol [RFC1928](https://datatracker.ietf.org/doc/html/rfc1928) for SOCKS5 specifies: "This new protocol extends the SOCKS Version 4 model to include UDP".

It means that DNS can be resolve on SOCKS5 proxy side and no need to lookup it locally at a client.

To fix it just replace the code above with the following:
```
switch (opts.protocol.replace(':', '')) {
	case 'socks4':
		lookup = true;
	// pass through
	case 'socks4a':
		type = 4;
		break;
	case 'socks': // no version specified, default to 5h
	case 'socks5':
	case 'socks5h':
		type = 5;
		break;
	default:
		throw new TypeError(`A "socks" protocol must be specified! Got: ${opts.protocol}`);
}
```

**Comment by jumoog** [comment]
This is not regulated by RFC1928 but comes from [CURLOPT_PROXY](https://curl.se/libcurl/c/CURLOPT_PROXY.html), which is a de facto standard. 

**Client resolves URL hostname**
socks4/socks5

**Proxy resolves URL hostname**
socks4a/socks5h
