### ISSUE TITLE
"username" not being used

### ISSUE THREAD

**Issue by rightaway** [TooTallNate/node-socks-proxy-agent#92]
It's possible to give `userId` or `username` https://github.com/TooTallNate/node-socks-proxy-agent/blob/master/src/index.ts#L82 but if you give `username` it doesn't get used. `username` should be used if it's given since it's used by the standard URL object.

**Comment by Kikobeats** [comment]
Hello,

`socks-proxy-agent` uses `socks` as dependency, and that's the way for passing the username:

https://github.com/JoshGlazebrook/socks/search?q=userid

**Comment by rightaway** [comment]
I'm not sure why it wasn't working before. If you pass `username` or `userId` both work because of `let userId = opts.userId ?? opts.username`. Can you update documentation to say both are possible?
